### ISSUE TITLE
FR: add custom label to ignore nodes from clab topo definitions

### ISSUE THREAD

**Issue by bortok** [netreplica/graphite#8]
Introduce a custom label to mark nodes in clab topo definitions yaml that should be ignored during visualization.

**Comment by bortok** [comment]
Use `graph-hide: yes` label in clab topology definition YAML like the following:
```Yaml
    graphite:
      kind: linux
      image: netreplica/graphite
      labels:
        graph-hide: yes
````
